fix: ensure digest is passed between actions

diff --git a/.github/actions/deploy/action.yml b/.github/actions/deploy/action.yml
--- a/.github/actions/deploy/action.yml
+++ b/.github/actions/deploy/action.yml
@@ -9,6 +9,13 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: validate digest
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.digest }}" ]; then
+          echo "Error: Digest is empty. Exiting deployment."
+          exit 1
+        fi
     - name: start minikube
       id: minikube
       uses: medyagh/setup-minikube@latest
